### ISSUE TITLE
Games doesn't show as installed

### ISSUE THREAD

**Issue by nduriez** [TBemme/galaxy-integration-nds#3]
I filled everything needed to be able to launch nDS game directly throug Galaxy 2.0 i think but in Galaxy 2. they doesn't show as installed 

my config.py looks like this : 
```python
game_list = ""
game_dat = ""
roms_path = "E:\\Jeux\\Emulateurs\\Nintendo DS\\Jeux"
emu_path = "E:\\Jeux\\Emulateurs\\Nintendo DS\\DeSmuME_X432R_x64.exe"
```

My NDS-list.txt :
```
0297 - Mario & Luigi - Partners in Time (Europe) (En,Fr,De,Es,It)
4268 - Mario & Luigi - Bowser's Inside Story (Europe) (En,Fr,De,Es,It)
5605 - Ookami Den (Europe).nds
```

corresponding rom names from NDS.dat :
```dat
0297 - Mario &amp; Luigi - Partners in Time (Europe) (En,Fr,De,Es,It).nds
4268 - Mario &amp; Luigi - Bowser's Inside Story (Europe) (En,Fr,De,Es,It)
5605 - Ookami Den (Europe)
```

My emulator folder is like this :
```Nintendo DS
     |_DeSmuME_X432R_x64.exe
     |_Jeux 
        |_0297 - Mario &amp; Luigi - Partners in Time (Europe) (En,Fr,De,Es,It)
        |_4268 - Mario &amp; Luigi - Bowser's Inside Story (Europe) (En,Fr,De,Es,It).nds
        |_5605 - Ookami Den (Europe).nds
```

**Comment by TBemme** [comment]
Hi, thanks for the detailed information about your set up.

One possible issue is that the path to your local games directory (roms_path) needs to end with '\\\\' in order for the plugin to successfully put the game paths together.

And, in the NDS-list.txt, it only needs the names of the games without the '.nds' file extension (so, your third game can just be "5605 - Ookami Den (Europe)". The plugin adds the file extension back when creating the game path by itself.)

Please let me know if these two changes fix the problem. Otherwise, it may help to see if there's any errors in the plugin logs file (in C:\ProgramData\GOG.com\Galaxy\Logs )

**Comment by nduriez** [comment]
I did both things, and now i can launch DS games perfectly, thank you for your help, 

However, if anyone encounter a similar issue, i'd like to point out that even tho in the *NDS.dat* file, the "&" character is displayed as "&amp;", for the game to be shown as installed and launchable, you must name your nds file and list it in *NDS-list.txt* as "&" 

Also, I think you should precise either in the *README* or in the *config.py* file that the Username is the thing that will be displayed in the GOG Galaxy 2.0 settings Integration tab, 
I personally used it to write the name of the emulator i'm using

**Comment by TBemme** [comment]
Glad that it's working now.

And thank you for letting me know about the "&" issue - this is something I unfortunately over-looked, because I assumed most people would use a Rom Manager program to generate their lists (which will automatically name the files with an "&" character), and I did not have any games with an "&" in the title when I was testing to realise this potential problem. I will very soon update the readme to address this.

I originally did not specify what the username is for, is because I was waiting to hear back from GOG staff about it - but it seems that it will only be used for what you see, the name listed in the Settings window. So, it can be named whatever you like.
